restart.exclude.spring-boot-starter=/spring-boot-starter-[\\w-]+/
restart.exclude.spring-boot-autoconfigure=/spring-boot-autoconfigure-[\\w-]+/
restart.exclude.spring-boot-actuator=/spring-boot-actuator[\\w-]*/
restart.exclude.mybatis-plus=/mybatis-plus-[\\w-]+/
restart.exclude.knife4j=/knife4j[\\w-]*/
